export enum MessageType {
    TRANSLATE = "TRANSLATE",
    SELECTION_TRANSLATE = "SELECTION_TRANSLATE",
    SELECTION_TRANSLATE_RESULT = "SELECTION_TRANSLATE_RESULT",

    ADD_GLOSSARY = "ADD_GLOSSARY",
    ADD_GLOSSARY_SUCCESS = "ADD_GLOSSARY_SUCCESS",
}